CREATE TABLE COLOR
(
	RGB INT NOT NULL,
	L FLOAT NOT NULL,
	A FLOAT NOT NULL,
	B FLOAT NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_COLOR ON COLOR (
	RGB
)
GO

CREATE TABLE COLOR_INDEX_L
(
	RGB INT NOT NULL,
	[HASH] INT NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_COLOR_INDEX_L ON COLOR_INDEX_L (
	[HASH]
)
GO

CREATE INDEX IDX1_COLOR_INDEX_L ON COLOR_INDEX_L (
	RGB
)
GO

CREATE TABLE COLOR_INDEX_A
(
	RGB INT NOT NULL,
	[HASH] INT NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_COLOR_INDEX_A ON COLOR_INDEX_A (
	[HASH]
)
GO

CREATE INDEX IDX1_COLOR_INDEX_A ON COLOR_INDEX_A (
	RGB
)
GO

CREATE TABLE COLOR_INDEX_B
(
	RGB INT NOT NULL,
	[HASH] INT NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_COLOR_INDEX_B ON COLOR_INDEX_B (
	[HASH]
)
GO

CREATE INDEX IDX1_COLOR_INDEX_B ON COLOR_INDEX_B (
	RGB
)
GO

CREATE TABLE PALETTE
(
	ID INT IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] NVARCHAR(2048) NOT NULL,
	RATE FLOAT NULL,
	CLUSTER INT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_PALETTE ON PALETTE (
	ID
)
GO

CREATE INDEX IDX1_PALETTE ON PALETTE (
	RATE
)
GO

CREATE TABLE PALETTE_COLOR
(
	PALETTE_ID INT NOT NULL,
	[ORDER] INT NOT NULL,
	RGB INT NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_PALETTE_COLOR ON PALETTE_COLOR (
	PALETTE_ID, [ORDER]
)
GO

CREATE TABLE PALETTE_THUMBNAIL
(
	PALETTE_ID INT NOT NULL,
	[ORDER] INT NOT NULL,
	[DATA] BINARY(2048) NOT NULL
)
GO

CREATE CLUSTERED INDEX IDX0_PALETTE_THUMBNAIL ON PALETTE_THUMBNAIL (
	PALETTE_ID, [ORDER]
)
GO

CREATE PROC UP_ADD_COLOR
@rgb AS INT,
@l AS FLOAT,
@a AS FLOAT,
@b AS FLOAT,
@l_hash AS INT,
@a_hash AS INT,
@b_hash AS INT
AS
BEGIN

	IF EXISTS(SELECT RGB FROM COLOR WHERE RGB = @rgb) RETURN
	
	INSERT INTO [COLOR]
           ([RGB]
           ,[L]
           ,[A]
           ,[B])
    VALUES (@rgb, @l, @a, @b)
     
    INSERT INTO [COLOR_INDEX_A]
          ([RGB]
          ,[HASH])
    VALUES (@rgb, @a_hash)
    
    INSERT INTO [COLOR_INDEX_B]
          ([RGB]
          ,[HASH])
    VALUES (@rgb, @b_hash)
    
    INSERT INTO [COLOR_INDEX_L]
          ([RGB]
          ,[HASH])
    VALUES (@rgb, @l_hash)
	
END           
GO

CREATE PROC UP_ADD_PALETTE
@desc NVARCHAR(2048),
@id INT OUTPUT
AS
BEGIN

	INSERT INTO [PALETTE]
           ([DESCRIPTION]
           ,[RATE])
    VALUES (@desc, NULL)

	SET @id = @@IDENTITY

END
GO

CREATE PROC UP_ADD_PALETTE_COLOR
@palette_id INT,
@order INT,
@rgb INT,
@clear BIT
AS
BEGIN

	IF EXISTS(SELECT RGB FROM PALETTE_COLOR WHERE (RGB = @rgb) AND (PALETTE_ID = @palette_id))
	BEGIN
	
		UPDATE PALETTE_COLOR SET [ORDER] = @order
		WHERE (RGB = @rgb) AND (PALETTE_ID = @palette_id)
		
	END
	ELSE
	BEGIN
	
		INSERT INTO [PALETTE_COLOR]
			   ([PALETTE_ID]
			   ,[ORDER]
			   ,[RGB])
		VALUES (@palette_id, @order, @rgb)
		
	END
	
	IF @clear = 1
	BEGIN
		DELETE FROM PALETTE_COLOR WHERE (PALETTE_ID = @palette_id) AND ([ORDER] > @order)
	END	

END
GO


CREATE PROC UP_ADD_THUMBNAIL
@palette_id INT,
@order INT,
@data BINARY(2048)
AS
BEGIN
	
	DELETE FROM PALETTE_THUMBNAIL WHERE (PALETTE_ID = @palette_id) AND ([ORDER] >= @order)
	
	INSERT INTO PALETTE_THUMBNAIL
           ([PALETTE_ID]
           ,[ORDER]
           ,[DATA])
     VALUES
           (@palette_id
           ,@order
           ,@data)

END
GO